---
- name: Creating jenkins user from ansible tower
  hosts: 172.31.88.63
  remote_user: ec2-user
  tasks:
  - name: Download jenkins cli jar
    get_url:
      url: http://localhost:8080/jnlpJars/jenkins-cli.jar 
      dest: /tmp/jenkins-cli.jar 
      mode: '0775'
      
  - name: Create Jenkins user / there is no uri(api) support in jenkins to create user
    shell:  echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("{{JENKINS_USER}}", "{{JENKINS_PASSWORD}}" )' | java -jar /tmp/jenkins-cli.jar -auth "{{JENKINS_ADMIN_USER}}":"{{JENKINS_ADMIN_PASSWORD}}"  -s http://localhost:8080/ groovy = 
    register: jenkinsUsers
  - debug: 
    var=jenkinsUsers
    when: jenkinsUsers.stdout != "{{JENKINS_USER}}"
  - mail:
      host: smtp.gmail.com
      port: 587
      username: "{{MAIL_ID}}"
      password: "{{MAIL_PASSWORD}}"
      to: "{{MAIL_TO}}"
      subject: User create
      body: 'User in Jenkins "{{ JENKINS_USER }}" has been successfully provisioned.'
