---
- hosts: 172.31.88.63
  - mail:
      host: smtp.gmail.com
      port: 587
      username: "{{MAIL_ID}}"
      password: "{{MAIL_PASSWORD}}"
      to: "{{MAIL_TO}}"
      subject: User create
      body: 'User in  "{{ MAIL_ID }}" has been successfully provisioned.'
